platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!
  pod 'SQLCipher', '~> 4.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end
